try {
	{body}
} catch ({exception}) {
	{body}
}
